"""Added URL for the posts

Revision ID: e0fe317a0c60
Revises: ad98bc194c2e
Create Date: 2023-06-14 20:40:27.987002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0fe317a0c60'
down_revision = 'ad98bc194c2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'monitored_users', ['id'])
    op.add_column('posts', sa.Column('url', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'posts', ['id'])
    op.create_unique_constraint(None, 'social_accounts', ['id'])
    op.create_unique_constraint(None, 'social_auths', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'social_auths', type_='unique')
    op.drop_constraint(None, 'social_accounts', type_='unique')
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_column('posts', 'url')
    op.drop_constraint(None, 'monitored_users', type_='unique')
    # ### end Alembic commands ###
